add documentation around the provider param in sales-tax-reporting
taxjar/taxjar-developers pull request #47
Opened 2021-02-04 16:44 UTC by ryan-lgtm

Let's avoid duplicate receipts/STT's/marketplace exempt confusion/provide a quick ref for customers. 😍

2021-02-04 16:47 UTC, ryan-lgtm commented
Quick link - https://deploy-preview-47--taxjar-developers.netlify.app/integrations/sales-tax-reporting/#section-provider

2021-02-04 16:56 UTC, cas27 requested changes

2021-02-04 16:56 UTC, cas27 commented on source/integrations/sales-tax-reporting.md
> +
we also support facebook

2021-02-04 16:56 UTC, cas27 commented on source/integrations/sales-tax-reporting.md
> +These e-commerce channels are marketplaces, and therefore marketplace exempt. The platform handles sales tax calculation and remittance on behalf of the seller.
This isnt the full story, as it depends on the state and transaction date.  Should we add something about there here?

2021-02-04 16:56 UTC, cas27 commented on source/integrations/sales-tax-reporting.md
> +**Note:** It is not necessary to call for sales tax calculations of marketplace orders or refunds. Because they are collected and remitted on behalf of the merchant by the marketplace platform, avoid
Again may not be true depending on state and date.

2021-02-04 17:32 UTC, ryan-lgtm commented on source/integrations/sales-tax-reporting.md
> +
@cas27 --

- added facebook
- removed the line regarding marketplace specified provider transactions being marketplace exempt
- replaced said line with an explanation that exemptions are dependent on state/date, with a link to the up-to-date marketing blog content on MF laws
- removed the bottom "note" -- they should hit /v2/taxes so we can determine if sales tax should be collected or not.

Thank you sir!

2021-02-09 17:23 UTC, fastdivision commented on source/integrations/sales-tax-reporting.md
> +
@ryan-lgtm We should probably mention Facebook in the API documentation "View Note" tooltips for the `provider` param as well. For this bullet list of supported providers, I'd drop the `; or` and `.` at the end.

2021-02-23 17:07 UTC, ryan-lgtm commented on source/integrations/sales-tax-reporting.md
> +
@fastdivision I think this should be good to go now if the explanation sounds good. I also have a PR up on taxjar-api-docs updating the tooltips for orders & refunds and the date in the changelog the feature was supported [here](https://github.com/taxjar/taxjar-api-docs/pull/94).
cc: @cas27

2021-04-12 23:47 UTC, fastdivision approved these changes
Looks good to me 👍

2021-04-13 15:13 UTC, cas27 approved these changes

2021-04-14 21:29 UTC, merged