Added NetSuite SuiteCommerce configuration details
taxjar/taxjar-developers pull request #63
Opened 2021-12-16 01:25 UTC by jordan-k-johnson

- Updated changelog
- Added details on how to enable SuiteCommerce cart tax calculations, with necessary steps for configuration.

2021-12-16 18:39 UTC, dallendalton requested changes

2021-12-16 18:39 UTC, dallendalton commented on source/integrations/guides/netsuite.md
> +In order to enable scriptable cart for each applicable website:
Looks like the markup might be a little broken here, and isn't showing as bullet points.

![image](https://user-images.githubusercontent.com/11321890/146429408-5f75f927-ec11-4eda-b536-c6f0307de6d4.png)

2021-12-17 23:28 UTC, jordan-k-johnson commented on source/integrations/guides/netsuite.md
> +In order to enable scriptable cart for each applicable website:
I realized that was caused by an initial line I added prior to each of the bulleted lists. I added a line break after each one, and now they look as expected. Thanks!

2021-12-18 00:15 UTC, sethobey-stripe approved these changes

2021-12-18 00:16 UTC, sethobey approved these changes
lgtm

2021-12-20 22:35 UTC, dallendalton approved these changes

2021-12-20 22:45 UTC, merged